package com.example.leet.september.week4;

/**
 *  Find the Difference
 * Given two strings s and t which consist of only lowercase letters.
 *
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 *
 * Find the letter that was added in t.
 *
 * Example:
 *
 * Input:
 * s = "abcd"
 * t = "abcde"
 *
 * Output:
 * e
 *
 * Explanation:
 * 'e' is the letter that was added.
 */
public class Day24 {

    public static char findTheDifference(String s, String t) {
        if(null == s || null == t)
            return ' ';
        int[] map = new int[26];
        for (char c : s.toCharArray()){
            map[c - 'a']++;
        }
        for (char c : t.toCharArray()){
            if(map[c - 'a']-- == 0)
                return c;
        }
        return ' ';
    }

    public static void main(String[] args) {
        System.out.println(findTheDifference("abcd", "abcde"));
        System.out.println(findTheDifference0("a", "aa"));
    }

    public static char findTheDifference0(String s, String t) {
        int sumS = 0, sumT = 0;
        char[] arrS = s.toCharArray();
        char[] arrT = t.toCharArray();
        for (int i = 0; i < arrS.length; i++) {
            sumS += arrS[i] - 'a';
            sumT += arrT[i] - 'a';
        }
        sumT += arrT[arrT.length - 1] - 'a';
        return (char) (sumT - sumS + 'a');
    }
}
